### ISSUE TITLE
Error when trying to plot 2D datausing bruker-utils together with Matplotlib: ValueError: Contour levels must be increasing when trying to plot 2D data

### ISSUE THREAD

**Issue by kulakarla** [5hulse/bruker_utils#1]
Hello,

`ValueError: Contour levels must be increasing when trying to plot 2d data`

the error is pretty self explanatory - with valid Bruker processed datasets (all the files that are required exist) I fail to create a 2D spectrum with matplotlib using a dataset imported with bruker-utils. I do not work with NMR experiments myself, therefore I don't know how Bruker data is exactly formatted. Currently under the assumption that this can be sorted? With some processed data it works.
Trying to use the library to create some plots.
Code used from the 2D plotting example https://5hulse.github.io/bruker_utils/content/usage.html#id1

Python version 3.12
Numpy version 1.26.4
bruker-utils version 0.0.1
matplotlib version 3.8.4

**Comment by simonhulse** [comment]
Hi there,

I suspect that there is not a file called `clevels` in your dataset directory. When this is the case, `BrukerDataset.contours` returns `None`, and this will lead to an error when you try to create the plot:
https://5hulse.github.io/bruker_utils/content/reference.html#bruker_utils.BrukerDataset.contours

You will have to manually create a list of contour levels to give to `ax.contour`. In NMR, it is common to set the contour levels as geometric sequence. You can achieve this as follows:
```python
nlevels = 10  # number of contour levels
base = 1.0  # lowest contour level
factor = 2.0  # scaling factor
# positive contours
levels = [base * n ** factor for n in range(1, nlevels + 1)] 
# include negative countours; if you don't need negative contours, you can comment this line out
levels = [-x for x in reversed(levels)] + levels

ax.contour(*shifts, spectrum, levels=levels, ...)
```
This example creates the following contour levels:
`[-100.0, -81.0, -64.0, -49.0, -36.0, -25.0, -16.0, -9.0, -4.0, -1.0, 1.0, 4.0, 9.0, 16.0, 25.0, 36.0, 49.0, 64.0, 81.0, 100.0]`
For your datasets, you'll need to tweak `nlevels`, `base`, and `factor` to suitable values. In particular, `base` can differ by many orders of magnitude going from one dataset to another.

Hope this helps!

**Comment by kulakarla** [comment]
Thank you for the quick reply @5hulse

The file `clevels` is present. I tried other libraries like https://miguelarbesu.xyz/post/nmrplot/, which by a quick investigation produce some levels by default themselves.

The clevels is present:
```
##TITLE= Parameter file, TopSpin 4.0.6
##JCAMPDX= 5.0
##DATATYPE= Parameter Values
##NPOINTS= 2	$$ modification sequence number
##ORIGIN= Bruker BioSpin GmbH
##OWNER= Group_mate
$$ 2019-05-01 23:33:24.242 +0200  Group_mate@neo500.kemi.uu.se
$$ /opt/topspin4.0.2/data/Group_mate/Daniel_U/UDA_12_011_CD3OD_500MHz/46/pdata/1/clevels
$$ process /opt/topspin4.0.6/prog/mod/proc2d
##$LEVELS= (0..255)
1293447680 -1293447680 3108658678.08 -3108658678.08 7471317878.75 -7471317878.75
17956487548.46 -17956487548.46 43156435090.9 -43156435090.9 103721726464
-103721726464 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
##$LEVSIGN= 3
##$MAXLEV= 6
##$METHOD= 0
##$NEGBASE= -1293447680
##$NEGINCR= 1.8
##$POSBASE= 1293447680
##$POSINCR= 1.8
##END=
```

Running with Bruker-utils with the example code given
```
import re
from bruker_utils import BrukerDataset
import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np

def format_nucleus(nucleus: str) -> str:
    """Format nucleus for matplotlib."""
    match = re.search(r'^<(\d+)([A-Z]+)>$', nucleus)
    number = match.group(1)
    symbol = match.group(2)
    return f'$^{{{number}}}${symbol}'

font = {'size': 8}
mpl.rc('font', **font)

dataset = BrukerDataset('../Compound_5/46/pdata/1')
print(dataset)
spectrum = dataset.data

shifts = dataset.get_samples()
levels = dataset.contours

fig = plt.figure(figsize=(4, 4))
ax = fig.add_axes([0.14, 0.12, 0.83, 0.85])
contour = ax.contour(*shifts, spectrum, levels=levels, colors='k', linewidths=0.6)

ax.set_xlim(30.39, 0)
ax.set_ylim(200, 0)

params = dataset.get_parameters(filenames=['acqus', 'acqu2s'])
xnuc = params['acqus']['NUC1']
ynuc = params['acqu2s']['NUC1']
ax.set_xlabel(f'{format_nucleus(xnuc)} (ppm)')
ax.set_ylabel(f'{format_nucleus(ynuc)} (ppm)')


# Save the figure to your preferred format
fig.show();
#fig.savefig('spectrum_2d.png', dpi=400)

```

Produces
```
ValueError: Contour levels must be increasing

```

With NMRglue, NMRium, nmrplot I get plots produced.

Thank you for the reply as I indeed have some learning to do here.

**Comment by simonhulse** [comment]
I must have assumed that contour levels are always stored in ascending order in the `clevels` file. The `contours` method simply reads the values of `$LEVELS` into a list with the same ordering (neglecting all the `0`s).

Replacing the line
```python
levels = dataset.contours
```
with
```python
levels = sorted(dataset.contours)
```
should fix this issue. I'll look at incorporating this into a new release.

**Comment by simonhulse** [comment]
I have just made a new release (0.0.2) which sorts the contour levels. You can either stick with 0.0.1 and apply the tweak I mentioned above, or switch to 0.0.2 with `pip install --upgrade bruker_utils`

**Comment by kulakarla** [comment]
@5hulse you are quick! Awesome man, I'll look into it :)
